### ISSUE TITLE
Is "frob :: forall a. F a -> F [a]" inherently ambiguous?

### ISSUE THREAD

**Issue by Icelandjack** [goldfirere/thesis#7]
[Here](https://github.com/goldfirere/thesis/blob/c1b82b8ba777d9de4c1ce0ffd57061746bf4aa68/tex/dep-haskell.lhs#L363) you claim that

``` haskell
frob :: forall a. F a -> F [a]
```

is inherently ambiguous but in the presence of type family dependency on `F` is that true?

**Comment by goldfirere** [comment]
No, I suppose not. I can clarify in the text. Thanks for pointing this out!
