### ISSUE TITLE
SubListProof & ElemProof can be marked injective

### ISSUE THREAD

**Issue by Icelandjack** [goldfirere/thesis#9]
Type families `SubListProof` and `ElemProof` can be made injective, does that help anywhere?

```haskell
type family
  SubListProof = (res :: SubList (xs :: [a]) (ys :: [a])) | res -> xs a where
  SubListProof = SubNil
  SubListProof = Keep SubListProof
  SubListProof = Drop SubListProof

type family
  ElemProof = (res :: EffElem eff a xs) | res -> eff a xs where
  ElemProof = Here
  ElemProof = There ElemProof
```

**Comment by goldfirere** [comment]
Perhaps, but I'm not keen on maintaining this repo as a "living document" -- so I'm going to close. If this code has been broken out into another package of mine, perhaps report there. Sorry!

**Comment by Icelandjack** [comment]
No problem, I'm not trying to change the code but trying to understand these new programming patterns and how they interact

**Comment by Icelandjack** [comment]
Err it exists [here](https://github.com/goldfirere/effects/blob/46249143f77429821ee10c0dd27852084cad15ba/Effects.hs#L68) so I'll just.. reopen the ticket or something? [ticket #1](https://github.com/goldfirere/effects/issues/1)
